import Head from 'next/head';
import {useDispatch, useSelector} from "react-redux";
import {useEffect} from "react";
import {getHomeContent, selectHomeContent} from "@/store/slices/content";
import {setLoader} from "@/store/slices/common";
import Reviews from "@/components/home/Reviews";
import Transportation from "@/components/home/Transportation";
import Customers from "@/components/home/Customers";
import Checkout from "@/components/home/Checkout";
import CommercialServices from "@/components/home/CommercialServices";
import LatestArticles from "@/components/home/LatestArticles";
import CalculationInfo from "@/components/quote/CalculationInfo";
import bgImg from "../../public/images/banner.png";
import QuoteForm from "@/components/home/QuoteForm";
import {useWindowSize} from "@/utils/hooks";
import QuoteSteps from "@/components/quote/quoteSteps";

export default function Home() {
    const dispatch = useDispatch();
    const {width} = useWindowSize();
    const content = useSelector(selectHomeContent);

    useEffect(() => {
        dispatch(setLoader(true));
        dispatch(getHomeContent())
            .then(() => dispatch(setLoader(false)))
    }, []);

    return (
        <>
            <Head>
                <title>Home</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
                <link rel="stylesheet" href="/css/react-phone-number-input/style.css"/>
            </Head>
            <main className="page-main">
                <div className="mainBanner m-padding" style={{backgroundImage: `url(${bgImg.src})`}}>
                    {width <= 768 ? <QuoteSteps/> : <QuoteForm/>}
                </div>
                <Reviews welcome={true}/>
                <Transportation/>
                <CalculationInfo/>
                <Customers/>
                <Checkout/>
                <CommercialServices/>
                {/*<Help/>*/}
                <LatestArticles/>
            </main>
        </>
    )
}
